### ISSUE TITLE
カーネルをアップデートするとWiFiが認識されなくなる

### ISSUE THREAD

**Issue by ryuichiueda** [ryuichiueda/raspimouse_book_info#1]
これ以上のバージョンでWiFi（wlan0）が認識されない。

```
ubuntu@ubuntu:~$ uname -a
Linux ubuntu 4.4.0-1046-raspi2 #53-Ubuntu SMP Sun Mar 5 13:25:01 UTC 2017 armv7l armv7l armv7l GNU/Linux
ubuntu@ubuntu:~$ iwconfig
・・・wlan0が表示されない・・・
```

**Comment by ryuichiueda** [comment]
今のところの対策は、自動アップデートを止める方法です。イメージをhttps://wiki.ubuntu.com/ARM/RaspberryPi からダウンロードしてSDカードにddした後、すぐにC.13.1「自動アップデートの抑制」でアップデートを止める方法が今のところ最良です。

また、その後すぐに

```
$ sudo apt purge cloud-init
```

の実行をお願いいたします。

今アップデートされているOSイメージについては、これから検証します。

**Comment by ryuichiueda** [comment]
続報ですが、カーネル本体でなく、あるパッケージがよくないみたいです。C.13.1項の「自動アップデートの抑制」の方が有効です。

**Comment by ishigem** [comment]
os_images.md で紹介されているUbuntu MATEのOSイメージ
https://tiryoh.com/blog/archives/1101 を使ったらwlan0を認識してくれました。

**Comment by ryuichiueda** [comment]
とりあえずアップデートを全て止めたイメージをアップしました。利用はこの本を練習するときだけということでお願いします。

https://lab.ueda.asia/misc/ubuntu-16.04-preinstalled-server-armhf+raspi3-ros-noupgrade-rtmouse-catkin.img.xz

**Comment by ryuichiueda** [comment]
今はアップデートしたカーネルでwlan0を復活させる方法がないか調べています。今日はもう時間切れかもしれません。確証を得ていませんがデバイスドライバがなくなっているような・・・

メモ: チップはBCM43438

**Comment by ryuichiueda** [comment]
対策をまとめました。

https://github.com/ryuichiueda/raspimouse_book_info/blob/master/trouble_reports/wifiproblem.md

**Comment by ryuichiueda** [comment]
現在、カーネルのダウングレードを試しています。

$ sudo apt install linux-image-4.4.0-1038-raspi2

**Comment by ishigem** [comment]
対処法1.2で、

２行のうち
$ echo linux-firmware-raspi2 hold | sudo dpkg --set-selections 
だけを実行して、そのあとの手順をsudo　apt　upgrade　まで行い
ROSのインストールは省略して、2.4.1節のwifiの設定を行ったところ、wlan0を認識しました。
uname -r は、4.4.0-1052-raspi2 でした。

ubuntu-MATEの方だと　4.4.38-v7+　です。

**Comment by ryuichiueda** [comment]
確認ありがとうございます！

**Comment by ryuichiueda** [comment]
https://wiki.ubuntu.com/ARM/RaspberryPi のイメージをインストールした後に行うべき手続きをシェルスクリプトにしました。当該する本の内容は、「ここにあるスクリプト使え」でよかったかもしれません orz

https://github.com/ryuichiueda/raspimouse_book_ubuntu_init/blob/master/after_os_install.bash

**Comment by ryuichiueda** [comment]
こちら閉じます。

**Comment by FurqanHabibi** [comment]
他の方法もあると思います。
https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=141834#p1152584
上記に書いてあるの通り、ラズパイの元のwifiのfirmwareを使うようにしたら、WiFiがまた認識されるようになります。
私が使ったコマンドは下記：
```
cd /lib/firmware/brcm/
sudo wget https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm80211/brcm/brcmfmac43430-sdio.bin -O brcmfmac43430-sdio.bin
sudo wget https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm80211/brcm/brcmfmac43430-sdio.txt -O brcmfmac43430-sdio.txt
```
これでカーネルがアップデートされても、上記のコマンドで問題が解決されると思います。

私は日本語がまだ勉強していますので、何か間違えると申し訳ございません。

**Comment by ryuichiueda** [comment]
@FurqanHabibi さん

こちらでも動作確認できました。ありがとうございます。
