### ISSUE TITLE
3章でsagmentation faultとでます

### ISSUE THREAD

**Issue by nakajob** [ryuichiueda/raspimouse_book_info#12]
質問です。
3章の距離センサの値を読み取る時にsagmentation faultになります。
ページ数は45P
cat /dev/rtlightsensor0
の部分です。
OSはUbuntu MATE16.04です。
修正されているデバイスドライバーを使っています。

ubuntu@ubuntu-desktop:~$ cat  /dev/rtlightsensor0 
Segmentation fault

別の問題で46Pの
echo 400 > /dev/rtmotor_raw_10
のコードを入力してもモータが回転しません。
通電のコードを打ち込むと、モーターが固定された状態になり手動で回らなくなります。
また、通電状態で放置しておくとモーターがとても高温になります。
どうすれば解決できるのか教えてください。

**Comment by ryuichiueda** [comment]
すみません今気づきました。

> ubuntu@ubuntu-desktop:~$ cat /dev/rtlightsensor0
Segmentation fault

こちらの問題は、デバイスドライバがOSと合ってない可能性があります。このOS上でコンパイルはしましたでしょうか？

> echo 400 > /dev/rtmotor_raw_10

こちらは「10」でなくて「l0」エルゼロです。

**Comment by ryuichiueda** [comment]
> 通電のコードを打ち込むと、モーターが固定された状態になり手動で回らなくなります。
> また、通電状態で放置しておくとモーターがとても高温になります。

これはステップモータの特性です。電源を入れるとデフォルトでブレーキのかかった状態になります。また、動かさなくても電気を食いますので、発熱が続きます。こまめに通電を解除するようなプログラムを書く必要があります。

**Comment by nakajob** [comment]
返答ありがとうございます。
echo 400 > /dev/rtmotor_raw_l0でやってみましたが、回りません。

再起動を数回行った結果、Segmentation faultのエラーは直りました。
しかし、今度はブザーが鳴らなくなりました。

**Comment by ryuichiueda** [comment]
echo 1 > /dev/rtmotoren0
echo 400 > /dev/rtmotor_raw_l0

でどうでしょう？

ブザーは・・・どうですかね。ハードの仕様ではモータ右、モータ左、ブザーは同時に2個までしか動かせないそうです。

> 再起動を数回行った結果、Segmentation faultのエラーは直りました。

やはりデバイスドライバのリビルドが必要そうです。

**Comment by nakajob** [comment]
コピー＆ペーストで行ってみましたがモーターは動きませんでした。

デバイスドライバのリビルドとはどうしたらいいのでしょうか？

**Comment by ryuichiueda** [comment]
書籍のC.10に書いてあったかと。

**Comment by nakajob** [comment]
リビルドを行ってみましたが変化なしです

**Comment by ryuichiueda** [comment]
んー。MATEの方は追ってないのでちょっと分からないです。ビルドしたカーネルモジュールがちゃんとinsmodされてますか？

**Comment by nakajob** [comment]
すみません、勉強不足で質問の意味が理解できてないです。

ubuntu@ubuntu-desktop:~/RaspberryPiMouse/src/drivers$ modinfo rtmouse.ko
filename: /home/ubuntu/RaspberryPiMouse/src/drivers/rtmouse.ko
description: Raspberry Pi Mouse device driver
version: 1:1.1
license: GPL
author: RT Corporation
srcversion: D61625F34F66EF9E38FCAF9
alias: spi;mcp3204
alias: i2c:rtcntl
alias: i2c:rtcntr
depends: 
vermagic : 4.4.38-v7+ SMP mod_unload modversions ARMv7

書籍に記載してある確認方法で試した出力結果ですが、これで問題ないでしょうか？

**Comment by ryuichiueda** [comment]
このrtmouse.koの作成時刻はビルドした時刻になってますか？（ubuntu-desktopとなっていますがラズパイマウスのRaspberry Piでしょうか）

**Comment by nakajob** [comment]
作成した時刻になっています。
ubuntu-desktopはラズパイマウスの名前です

**Comment by ryuichiueda** [comment]
そうなると・・・Ubuntu Serverで試していただければと。

http://file.ueda.tech/RPIM_BOOK/
の
ubuntu-16.04-preinstalled-server-armhf+raspi3-upgradable-ROS-20171223.img.xz
がROSインストール済みのOSのイメージファイルです。

インストール方法は2.1.3の方法で、ファイル名を上記のものにしてやってみていただければと。

**Comment by nakajob** [comment]
やってみます。

**Comment by nakajob** [comment]
ubuntu-16.04-preinstalled-server-armhf+raspi3-upgradable-ROS-20171223.img.xz
書き込みましたがモニターに何も出力されません。
緑のLEDは点滅をしてます。
私が最初にUbuntu Serverをインストールしようとした時と同じ症状です。

**Comment by nakajob** [comment]
モニターを変更したら出力されました。

**Comment by nakajob** [comment]
2.1.6の項目のupgradeで詰まりました。
`ubuntu@ubuntu:~$ sudo apt upgrade 
パッケージリストを読み込んでいます... 完了
依存関係ツリーを作成しています                
状態情報を読み取っています... 完了
アップグレードパッケージを検出しています... 完了
以下のパッケージが自動でインストールされましたが、もう必要とされていません:
  libllvm4.0
これを削除するには 'sudo apt autoremove' を利用してください。
以下のパッケージはアップグレードされます:
  linux-firmware
アップグレード: 1 個、新規インストール: 0 個、削除: 0 個、保留: 0 個。
112 個のパッケージが完全にインストールまたは削除されていません。
45.5 MB のアーカイブを取得する必要があります。
この操作後に追加で 90.7 MB のディスク容量が消費されます。
続行しますか? [Y/n] y
取得:1 http://ports.ubuntu.com/ubuntu-ports xenial-updates/main armhf linux-firmware all 1.157.16 [45.5 MB]
45.5 MB を 20秒 で取得しました (2,230 kB/s)                                                          
(データベースを読み込んでいます ... 現在 156574 個のファイルとディレクトリがインストールされています。)
.../linux-firmware_1.157.16_all.deb を展開する準備をしています ...
linux-firmware (1.157.16) で (1.157 に) 上書き展開しています ...
dpkg: アーカイブ /var/cache/apt/archives/linux-firmware_1.157.16_all.deb の処理中にエラーが発生しました (--unpack):
 '/lib/firmware/brcm/brcmfmac43430-sdio.bin' を上書きしようとしています。これはパッケージ linux-firmware-raspi2 1.20161020-0ubuntu1~0.2~rpi3 にも存在します
dpkg-deb: エラー: サブプロセス ペースト がシグナル (Broken pipe) によって強制終了されました
処理中にエラーが発生しました:
 /var/cache/apt/archives/linux-firmware_1.157.16_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by ryuichiueda** [comment]
これで動きませんか？このエラーは私が少し設定をいじったので出てしまうのですが、おそらく他のパッケージはインストールできるはずです。エラー出すような設定をして申し訳ないですが・・・

**Comment by nakajob** [comment]
返信が遅くなり申し訳ありませんでした。
upgrade以外は問題なく動作しています。
モータも回りましたし、ブザーもなりました。

このイメージファイルはROSがインストールされている以外は、本に記載されているイメージファイルと一緒なのでしょうか？
現在は3章の「デバイスドライバの自動化」の項目を行っています。

**Comment by ryuichiueda** [comment]
> このイメージファイルはROSがインストールされている以外は、本に記載されているイメージファイルと一緒なのでしょうか？

一緒になるように作ってあります。また何か違うと思ったら言っていただければと。

**Comment by nakajob** [comment]
わかりました。
この度は親切に対応していただきありがとうございます。

**Comment by nakajob** [comment]
すいません、教えてください。
突然インターネットにつながらなくなりました。
有線でなら繋がります。
sudo service networking restart
でネットワークの再起動を行おうとすると
Job for networking.service failed because the control process exited with error code. See "systemctl status networking.service" and "journalctl -xe" for details.
と出力されます。
エラーの文章にある
systemctl status networking.service
を入力すると

● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor prese
  Drop-In: /run/systemd/generator/networking.service.d
           └─50-insserv.conf-$network.conf
   Active: failed (Result: exit-code) since 火 2018-03-06 07:29:32 UTC; 40s ago
     Docs: man:interfaces(5)
  Process: 17648 ExecStart=/sbin/ifup -a --read-environment (code=exited, status
  Process: 17641 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && 
 Main PID: 17648 (code=exited, status=1/FAILURE)

 3月 06 07:29:32 ubuntu wpa_supplicant[17751]: nl80211: Driver does not support 
 3月 06 07:29:32 ubuntu wpa_supplicant[17751]: nl80211: deinit ifname=wlan1 disa
 3月 06 07:29:32 ubuntu wpa_supplicant[17751]: Could not read interface wlan1 fl
 3月 06 07:29:32 ubuntu ifup[17648]: /etc/network/if-pre-up.d/wpasupplicant: 120
 3月 06 07:29:32 ubuntu ifup[17648]: run-parts: /etc/network/if-pre-up.d/wpasupp
 3月 06 07:29:32 ubuntu ifup[17648]: Failed to bring up wlan1.
 3月 06 07:29:32 ubuntu systemd[1]: networking.service: Main process exited, cod
 3月 06 07:29:32 ubuntu systemd[1]: Failed to start Raise network interfaces.
 3月 06 07:29:32 ubuntu systemd[1]: networking.service: Unit entered failed stat
 3月 06 07:29:32 ubuntu systemd[1]: networking.service: Failed with result 'exit
lines 1-20/20 (END)

こういった出力が返ってきます。

ifconfigで無線の内容を見ようとしても無線の内容は出力されません。

iwconfigでは以下の通りです

wlan0     IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
lo        no wireless extensions.

eth0      no wireless extensions.

かれこれ５時間以上格闘していますがさっぱり分かりません。
助けてください。

**Comment by ryuichiueda** [comment]
ログ中にwlan1とありますが、設定ファイルでwlan0じゃなくてwlan1と書いてないでしょうか？

あと、これはこの前のissue出ないので別のissueを立てていただければと。

**Comment by nakajob** [comment]
わかりました
