### ISSUE TITLE
無線lanが繋がらなくなりました。

### ISSUE THREAD

**Issue by nakajob** [ryuichiueda/raspimouse_book_info#13]
新しくたてました。
wlan1は自分で解決方法を調べているときに試したものです。
現在の設定は以下の通りです。

/etc/network/interfaces

auto wlan0

iface wlan0 inet static
address 192.168.11.8
netmask 255.255.255.0
#gateway 172.16.110.1
dns-nameservers 172.16.1.62

wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

wireless-power off

ubuntu@ubuntu:~$ cat /etc/wpa_supplicant/wpa_supplicant.conf 

network={
	ssid="MYSSID"
	#psk="MYpass"
	psk=553eaa25c92af0cb5f23c3cd36c3209186fe7fbf21fa8a4364bcc2588b046754
}

**Comment by ryuichiueda** [comment]
これでログはどうでますか？

**Comment by nakajob** [comment]
ubuntu@ubuntu:~$ sudo service networking restart 
Job for networking.service failed because the control process exited with error code. See "systemctl status networking.service" and "journalctl -xe" for details

ubuntu@ubuntu:~$ systemctl status networking.service
● networking.service - Raise network interfaces
   Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/generator/networking.service.d
           └─50-insserv.conf-$network.conf
   Active: failed (Result: exit-code) since 火 2018-03-06 08:40:33 UTC; 3min 19s ago
     Docs: man:interfaces(5)
  Process: 19220 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=1/FAILURE)
  Process: 19213 ExecStartPre=/bin/sh -c [ "$CONFIGURE_INTERFACES" != "no" ] && [ -n "$(ifquery --re
 Main PID: 19220 (code=exited, status=1/FAILURE)

 3月 06 08:40:33 ubuntu dhclient[19243]: DHCPREQUEST of 192.168.11.3 on eth0 to 255.255.255.255 port
 3月 06 08:40:33 ubuntu dhclient[19243]: DHCPACK of 192.168.11.3 from 192.168.11.1
 3月 06 08:40:33 ubuntu ifup[19220]: RTNETLINK answers: File exists
 3月 06 08:40:33 ubuntu ifup[19220]: bound to 192.168.11.3 -- renewal in 65272 seconds.
 3月 06 08:40:33 ubuntu ifup[19220]: RTNETLINK answers: File exists
 3月 06 08:40:33 ubuntu ifup[19220]: Failed to bring up eth0.
 3月 06 08:40:33 ubuntu systemd[1]: networking.service: Main process exited, code=exited, status=1/F
 3月 06 08:40:33 ubuntu systemd[1]: Failed to start Raise network interfaces.
 3月 06 08:40:33 ubuntu systemd[1]: networking.service: Unit entered failed state.
 3月 06 08:40:33 ubuntu systemd[1]: networking.service: Failed with result 'exit-code'.

**Comment by ryuichiueda** [comment]
ifupに失敗してますね。

**Comment by ryuichiueda** [comment]
sudo ifup wlan0をするとどうなりますか？

**Comment by nakajob** [comment]
なにも出力されません

ubuntu@ubuntu:~$ sudo ifdown wlan0 
ubuntu@ubuntu:~$ sudo ifup wlan0

**Comment by ryuichiueda** [comment]
そのあとifconfigかip addrしたらどうなります？

**Comment by nakajob** [comment]
ubuntu@ubuntu:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:86:af:5d brd ff:ff:ff:ff:ff:ff
    inet 192.168.11.3/24 brd 192.168.11.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 172.16.110.58/24 brd 172.16.110.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ba27:ebff:fe86:af5d/64 scope link 
       valid_lft forever preferred_lft forever
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether b8:27:eb:d3:fa:08 brd ff:ff:ff:ff:ff:ff
    inet 192.168.11.3/24 brd 192.168.11.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet 192.168.11.8/24 brd 192.168.11.255 scope global secondary wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::ba27:ebff:fed3:fa08/64 scope link 
       valid_lft forever preferred_lft forever


ubuntu@ubuntu:~$ ifconfig
eth0      Link encap:イーサネット  ハードウェアアドレス b8:27:eb:86:af:5d  
          inetアドレス:192.168.11.3  ブロードキャスト:192.168.11.255  マスク:255.255.255.0
          inet6アドレス: fe80::ba27:ebff:fe86:af5d/64 範囲:リンク
          UP BROADCAST RUNNING MULTICAST  MTU:1500  メトリック:1
          RXパケット:34475 エラー:0 損失:0 オーバラン:0 フレーム:0
          TXパケット:6710 エラー:0 損失:0 オーバラン:0 キャリア:0
          衝突(Collisions):0 TXキュー長:1000 
          RXバイト:5341258 (5.3 MB)  TXバイト:1500390 (1.5 MB)

lo        Link encap:ローカルループバック  
          inetアドレス:127.0.0.1  マスク:255.0.0.0
          inet6アドレス: ::1/128 範囲:ホスト
          UP LOOPBACK RUNNING  MTU:65536  メトリック:1
          RXパケット:0 エラー:0 損失:0 オーバラン:0 フレーム:0
          TXパケット:0 エラー:0 損失:0 オーバラン:0 キャリア:0
          衝突(Collisions):0 TXキュー長:1 
          RXバイト:0 (0.0 B)  TXバイト:0 (0.0 B)

wlan0     Link encap:イーサネット  ハードウェアアドレス b8:27:eb:d3:fa:08  
          inetアドレス:192.168.11.3  ブロードキャスト:192.168.11.255  マスク:255.255.255.0
          inet6アドレス: fe80::ba27:ebff:fed3:fa08/64 範囲:リンク
          UP BROADCAST RUNNING MULTICAST  MTU:1500  メトリック:1
          RXパケット:3614 エラー:0 損失:136 オーバラン:0 フレーム:0
          TXパケット:33 エラー:0 損失:0 オーバラン:0 キャリア:0
          衝突(Collisions):0 TXキュー長:1000 
          RXバイト:622415 (622.4 KB)  TXバイト:3750 (3.7 KB)

**Comment by nakajob** [comment]
現在有線で接続しています

**Comment by ryuichiueda** [comment]
eth0とwlan0のIPアドレスが同じですね。

**Comment by nakajob** [comment]
それぞれの設定です。

auto eth0

iface eth0 inet static
address 172.16.110.58
netmask 255.255.255.0
gateway 172.16.110.1
dns-nameserver 172.16.1.62

auto wlan0

iface wlan0 inet static
address 192.168.11.8
netmask 255.255.255.0
#gateway 172.16.110.1
dns-nameservers 172.16.1.62

wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf

wireless-power off

**Comment by ryuichiueda** [comment]
wlan0は生きてますね。以下を試してみていただければと。

1. 何かあったときのためにモニタにつなげられるようにする。
2. wlan0だけ立ち上がるように有線の設定をinterfacesファイルから消す（コメントアウト）
3. 再起動

**Comment by nakajob** [comment]
モニタは用意しています。
有線の設定をコメントアウトしました。
再起動しました。
有線接続が切れたためなのかSSH接続できなくなりました。

**Comment by nakajob** [comment]
無線のみの状態でもping は送れています。

**Comment by nakajob** [comment]
ping 192.168.11.8

PING 192.168.11.8 (192.168.11.8) 56(84) bytes of data.
64 bytes from 192.168.11.8: icmp_seq=1 ttl=128 time=2.80 ms
64 bytes from 192.168.11.8: icmp_seq=2 ttl=128 time=3.48 ms
64 bytes from 192.168.11.8: icmp_seq=3 ttl=128 time=3.67 ms

**Comment by ryuichiueda** [comment]
IPアドレスをwlan0のものに変えてsshすれば繋がるはずです。

**Comment by nakajob** [comment]
無線のipアドレスは設定では192.168.11.8になっているのでこうだと思うのですが
何かやりかたを間違えているのでしょうか？
今まではこのやり方でした。

ubutnu@ubuntu-virtual-machine:~$ ssh ubuntu@192.168.11.8
ssh: connect to host 192.168.11.8 port 22: Connection refused

**Comment by ryuichiueda** [comment]
ちょっと私もわからなくなってきたのですが、gateway 172.16.110.1に#があるのが気になりますね。

**Comment by nakajob** [comment]
調べたときにgatewayが悪さをするっていうのがあったのでコメントアウトしていました。
解除してもう一度やってみます

**Comment by nakajob** [comment]
再起動して試みましたが同じ結果でした。

**Comment by ryuichiueda** [comment]
DHCPに設定を書き直してやってみてください。IPはモニタでご調査を。

**Comment by nakajob** [comment]
今振っているIPアドレスがほかの人に使われている状態でした。
アドレスを振りなおしたらうまくいきました。
ご迷惑をおかけしました。

**Comment by ryuichiueda** [comment]
はいどうもー
