### ISSUE TITLE
13章での分担処理の項目

### ISSUE THREAD

**Issue by nakajob** [ryuichiueda/raspimouse_book_info#14]
13章の最後の部分でのラズパイとデスクトップとの分担作業をするときのランチファイルを実行したときにデスクトップ側でエラーが発生するのですがどうしてでしょうか？
pingは通ります。
以下エラー内容です

... logging to /home/youtheng/.ros/log/4ee8f5b4-2bfe-11e8-9045-b827eb86af5d/roslaunch-youtheng-virtual-machine-6790.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Unable to contact my own server at [http://note:53060/].
This usually means that the network is not configured properly.

A common cause is that the machine cannot ping itself.  Please check
for errors by running:

	ping note

For more tips, please see

	http://www.ros.org/wiki/ROS/NetworkSetup

The traceback for the exception was written to the log file

**Comment by ryuichiueda** [comment]
エラーログに書いてあるように、

```
ping note
```

を試していただけますか？

**Comment by nakajob** [comment]
問題なく動作します

ubuntu@ubuntu:~$ ping note
PING note (192.168.11.6) 56(84) bytes of data.
64 bytes from note (192.168.11.6): icmp_seq=1 ttl=128 time=2.66 ms
64 bytes from note (192.168.11.6): icmp_seq=2 ttl=128 time=5.94 ms
64 bytes from note (192.168.11.6): icmp_seq=3 ttl=128 time=5.76 ms
64 bytes from note (192.168.11.6): icmp_seq=4 ttl=128 time=5.72 ms
64 bytes from note (192.168.11.6): icmp_seq=5 ttl=128 time=5.67 ms
64 bytes from note (192.168.11.6): icmp_seq=6 ttl=128 time=6.06 ms
^C
--- note ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5008ms
rtt min/avg/max/mdev = 2.663/5.305/6.066/1.192 ms

**Comment by ryuichiueda** [comment]
あとはラズパイ側のマスタのURLが合ってないというのが原因としては可能性が大きいですね。

**Comment by nakajob** [comment]
パソコン側からのpingです。
youtheng@youtheng-virtual-machine:~$ ping raspberry
PING raspberry (192.168.11.168) 56(84) bytes of data.
64 bytes from raspberry (192.168.11.168): icmp_seq=1 ttl=128 time=5.80 ms
64 bytes from raspberry (192.168.11.168): icmp_seq=2 ttl=128 time=5.72 ms
64 bytes from raspberry (192.168.11.168): icmp_seq=3 ttl=128 time=6.86 ms
64 bytes from raspberry (192.168.11.168): icmp_seq=4 ttl=128 time=6.50 ms
64 bytes from raspberry (192.168.11.168): icmp_seq=5 ttl=128 time=6.78 ms
^C
--- raspberry ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4008ms
rtt min/avg/max/mdev = 5.729/6.337/6.862/0.485 ms

ラズパイとパソコン側に記述しているものをコピーしたものです。

export ROS_MASTER_URI=http://raspberry:11311
export ROS_HOSTNAME=note

export ROS_MASTER_URI=http://raspberry:11311
export ROS_HOSTNAME=raspberry

**Comment by ryuichiueda** [comment]
最初のログでノートPC側にマスタが立ち上がっているようにも読めるのですがどうでしょうか？

**Comment by nakajob** [comment]
ノート側でのランチファイルの内容です

<launch>
  <arg name="scan_topic" default="/scan" />
  <arg name="odom_topic" default="/odom" />

  <node pkg="gmapping" type="slam_gmapping" name="slam_gmapping" output="screen">
    <param name="base_frame" value="base_link"/>
    <param name="odom_frame" value="odom"/>

    <param name="maxUrange" value="4.0"/>
    <param name="maxRange" value="4.0"/>

    <param name="srr" value="0.3"/>
    <param name="srt" value="0.1"/>
    <param name="str" value="0.1"/>
    <param name="stt" value="0.3"/>

    <param name="particles" value="100"/>
  </node>
</launch>

実行手順はまずラズパイ側で
roslaunch pimouse_slam slam_remote_robot.launch 

その後ノート側で
 roslaunch pimouse_slam slam_remote_desktop.launch 
この手順で実行しています

**Comment by ryuichiueda** [comment]
すみません。回答になってないのですが、もう一度まっさらな状態から試していただくしかないような気がします。

**Comment by nakajob** [comment]
まっさらな状態というのはどの状態でしょうか？

質問の意味が理解できていなくて申し訳ないです。
マスタが立ち上がっているのを確認するためには何をすればわかるのでしょうか？

**Comment by ryuichiueda** [comment]
> マスタが立ち上がっているのを確認するためには何をすればわかるのでしょうか？

こちらも含めて、手順の確認のためにOSのセッティングから本書を試していただければと。

**Comment by ryuichiueda** [comment]
あとは両方の/etc/hostsの確認でしょうか・・・

ところで、その前にrvizはラズパイと通信できましたでしょうか？

**Comment by ryuichiueda** [comment]
それから、ローンチファイルに

```
<param name="maxUrange" value="4.0"/>
<param name="maxRange" value="4.0"/>

<param name="srr" value="0.3"/>
<param name="srt" value="0.1"/>
<param name="str" value="0.1"/>
<param name="stt" value="0.3"/>

<param name="particles" value="100"/>
```
しか書いてないとしたら、それは動きません。

**Comment by nakajob** [comment]
/etc/hostsは
ノート側

youtheng@youtheng-virtual-machine:~$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	youtheng-virtual-machine

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

192.168.11.168 raspberry
192.168.11.6 note

ラズパイ側
ubuntu@ubuntu:~$ cat /etc/hosts
127.0.0.1 localhost
127.0.0.1 ubuntu


::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

192.168.11.168 raspberry
192.168.11.6 note

となっています。

ローンチファイルはなぜか今回張り付けたときにパラメータの部分のみになっていますが、ファイルには教材に書いてある通りに作っています。

**Comment by ryuichiueda** [comment]
ノート側が仮想マシンになっているのが気になりますが、このログに尽きると思います。別のノートPCで試す等、少し試行錯誤が必要かと。それから、rvizと通信できたかどうか、もう一度確認したく。

> Unable to contact my own server at [http://note:53060/].
> This usually means that the network is not configured properly.

**Comment by nakajob** [comment]
slam_stand_alone.launchのみでの起動方法でノート側でRvizでの通信は確認できています。
（センサの前で障害物などを置いたときに物があることを正しく検知していました）

しかし、地図作成を行っても正しい地図が作成されません。
最初のスキャンだけで地図を作成すると見えている範囲での正しい地図が作成されるのですが、移動すると正常な地図になりません。
ラズパイ側に前進の命令を送ってもタイヤが少し空回りしてまっすぐに進めていないからではないかと考えています。
測域センサは書籍ではUSBタイプでしたが用意できたのがイーサネットタイプのUST-10のみでしたのでそのセンサを使用しています。

**Comment by ryuichiueda** [comment]
状況は半分程度わかりました。UST-10は使ったことがないのでちょっと返答は難しいです。また、コマンド操作やログの収集等は本書でも触れていますので、もう一度ご確認をお願いいたします。

**Comment by nakajob** [comment]
ロボットをバックさせたときの値です
誤差はあまりないように見えます。

  pose: 
    position: 
      x: -0.299992239475
      y: 0.0
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

- Translation: [-0.300, 0.000, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
            in RPY (radian) [0.000, -0.000, 0.000]
            in RPY (degree) [0.000, -0.000, 0.000]

こちらが左前に進んでいるときの出力です。

  pose: 
    position: 
      x: -0.174213691115
      y: -0.0408460820719
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.345951182617
      w: 0.938252513584

- Translation: [-0.174, -0.041, 0.000]
- Rotation: in Quaternion [0.000, 0.000, -0.346, 0.938]
            in RPY (radian) [0.000, 0.000, -0.707]
            in RPY (degree) [0.000, 0.000, -40.480]

**Comment by ryuichiueda** [comment]
すみません。なるべくご期待には添いたいのですが、もう少し私が答えるべきことをはっきりさせてから書き込んでいただければ幸いです。ご質問が発散しているかと。著者が応えるべき範囲を超えていると考えております。

**Comment by ryuichiueda** [comment]
このissueに関しては、以下のコメント14の内容につきます。PC側がRaspberry Piと通信できておりません。また、この部分は私の方で何度も通信できることを確認しており、何かソフトのバージョンアップで新しい状況が発生したという確証がないと、「本の内容でお願いします」としか言いようがない状況です。

https://github.com/ryuichiueda/raspimouse_book_info/issues/14#issuecomment-376398639

**Comment by nakajob** [comment]
申し訳ありませんでした。
もう少し勉強してきます。

**Comment by ryuichiueda** [comment]
仮想マシンだとちょっと私もなんとも言えませんので、ネイティブ環境か、あるいは別のラズパイからやってみるとよろしいかと。

スタンドアローンで地図ができないのは、少し処理を待つと良いかもしれません。あとはひたすらデバッグです。

**Comment by nakajob** [comment]
別のissueで聞くべきでしょうし、試していないとわからないと思いますが最後にひとつだけ質問させてください。
測域センサはイーサネットタイプでも問題はないのでしょか？

**Comment by ryuichiueda** [comment]
センサがイーサネットなのは、データが読めているなら問題ないんじゃないかと思います。速度の問題はあるかもしれませんが・・・

**Comment by nakajob** [comment]
仮想環境ではないパソコンを用意したら無事に動作しました。

ご迷惑をお掛けしました。

**Comment by ryuichiueda** [comment]
よかったです！では、issueを閉めます。
