### ISSUE TITLE
13章、ラズパイとデスクトップとの分担作業をするときのLaunch file

### ISSUE THREAD

**Issue by ykknkgw** [ryuichiueda/raspimouse_book_info#15]
お客様より下記質問がありましたので共有します。
＝＝＝
このロボットを購入するときに同時に「Raspberry Piで学ぶROSロボット入門」という書籍も同時に購入したのですが13章の後半にある、ラズパイとデスクトップとの分担作業をするときのランチファイルを実行したときにデスクトップ側でエラーが発生するのですが原因が分かりません教えてください。

以下エラー内容です

... logging to /home/youtheng/.ros/log/4ee8f5b4-2bfe-11e8-9045-b827eb86af5d/roslaunch-youtheng-virtual-machine-6790.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Unable to contact my own server at [http://note:53060/].
This usually means that the network is not configured properly.

A common cause is that the machine cannot ping itself. Please check
for errors by running:

ping note
For more tips, please see

http://www.ros.org/wiki/ROS/NetworkSetup
The traceback for the exception was written to the log file

またエラーログにある通りのpingを試した結果です

ubuntu@ubuntu:~$ ping note
PING note (192.168.11.6) 56(84) bytes of data.
64 bytes from note (192.168.11.6): icmp_seq=1 ttl=128 time=2.66 ms
64 bytes from note (192.168.11.6): icmp_seq=2 ttl=128 time=5.94 ms
64 bytes from note (192.168.11.6): icmp_seq=3 ttl=128 time=5.76 ms
64 bytes from note (192.168.11.6): icmp_seq=4 ttl=128 time=5.72 ms
64 bytes from note (192.168.11.6): icmp_seq=5 ttl=128 time=5.67 ms
64 bytes from note (192.168.11.6): icmp_seq=6 ttl=128 time=6.06 ms
^C
--- note ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5008ms
rtt min/avg/max/mdev = 2.663/5.305/6.066/1.192 ms

パソコン側からのpingです。
youtheng@youtheng-virtual-machine:~$ ping raspberry
PING raspberry (192.168.11.168) 56(84) bytes of data.
64 bytes from raspberry (192.168.11.168): icmp_seq=1 ttl=128 time=5.80 ms
64 bytes from raspberry (192.168.11.168): icmp_seq=2 ttl=128 time=5.72 ms
64 bytes from raspberry (192.168.11.168): icmp_seq=3 ttl=128 time=6.86 ms
64 bytes from raspberry (192.168.11.168): icmp_seq=4 ttl=128 time=6.50 ms
64 bytes from raspberry (192.168.11.168): icmp_seq=5 ttl=128 time=6.78 ms
^C
--- raspberry ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4008ms
rtt min/avg/max/mdev = 5.729/6.337/6.862/0.485 ms

ラズパイとパソコン側に記述しているものをコピーしたものです。

export ROS_MASTER_URI=http://raspberry:11311
export ROS_HOSTNAME=note

export ROS_MASTER_URI=http://raspberry:11311
export ROS_HOSTNAME=raspberry

**Comment by ryuichiueda** [comment]
ありがとうございます。本件、https://github.com/ryuichiueda/raspimouse_book_info/issues/14 と同じ課題です。仮想マシンをご使用中でポートの関係かなーと考えてますが、なんとも言えません。

**Comment by ryuichiueda** [comment]
こちらは閉じさせていただきます。
