### ISSUE TITLE
Wifi に接続できました。大変感謝です。

### ISSUE THREAD

**Issue by Uramaya** [ryuichiueda/raspimouse_book_info#17]
上田さん、
わたしは先日raspberrypiがwifi に接続できないとお問い合わせいたした浦です。

お陰さまで、こちらのosimageを使った所接続できました。

しかし部分的に英語が四角に表示されるのですが、原因はご存じですか。

いつもありがとうございます。

浦摩耶

**Comment by ryuichiueda** [comment]
これはですね、フォントがないですね。もしかしてHDMIで接続して画面を見られてますか？

**Comment by Uramaya** [comment]
上田さん、こんばんは！
お返事ありがとうございます。

はい、HDMI で接続しています。

エビデンス写真は以下の通りです。
https://1drv.ms/f/s!AsMhztcyRB2OvzlW8Pqb2hoP5ng7

ありがとうございます！
浦摩耶

**Comment by ryuichiueda** [comment]
ssh接続すると文字が見えると思います。

**Comment by Uramaya** [comment]
上田さん、こんばんは！
了解です！
お陰さまでSSHに接続でき文字が通常通り表示されました。
感謝感激です。
