### ISSUE TITLE
Raspberrypi mouse  device driver が効かない

### ISSUE THREAD

**Issue by Uramaya** [ryuichiueda/raspimouse_book_info#18]
上田さん、こんにちは😃
いつもお世話になっております。
すみません、またお邪魔しました。

実は昨日raspberrypi mouse にdevice driver を入れたのですが、エラーは全然出ずに、
led ライトは通常に動きましたが、
センサーは何をかざしても出力される値は　0000
そして音は全く出ません。
モーターもコマンドを入力しても動かないですので、
rtmouse.koをリビルトしてみましたが同じ結果でした。
色々調べましたが解決できず、
またお尋ねいたしました。
何度もすみません😣💦

**Comment by ryuichiueda** [comment]
んーちょっと情報がないのでなんとも言えないのですが、初めて聞く症状です。なにか手がかりはあるでしょうか。（同じ症例がいくつも報告されないとちょっと私は動きにくいです。。）

**Comment by Uramaya** [comment]
上田さん、こんばんは！
浦です。
わざわざ忙しいところ、お返事をありがとうございます。

先ほどまた試してみました。
（１）device driver を設置
⇒設置したエビデンス写真
．rtmouse.koをinsmod：
https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/42855169_331617264067544_5179408702716772352_n.png?_nc_cat=104&oh=423e9516e6e92f5bca6d3dc61054913c&oe=5C18ECB2

．ls -l /sys/class/gpio/
https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/42912125_2117363228515582_6196333018538311680_n.png?_nc_cat=110&oh=dc59e1c4bfe7e4479172ec99b3b9dfa6&oe=5C5566E0
試したところ、昨日と同じく順調にいってる感じです。

（２）コマンドでraspberry pi mouse を動かしてみる。
-LEDはコマンド通り光り
-BEEP音も通常になりました。

（３）しかしレイザーは何の障害物や手をかざしても（どの方向からも）、
永遠に0000しか返って来ません。
⇒エビデンス
https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/42903832_146440296305714_6223460805073960960_n.png?_nc_cat=103&oh=0e515b65ef564b2037cb6aac4c2ced5e&oe=5C16BDE0

（４）モーターのスイッチをオンにし、
コマンドを入れても、モーターに小さな動く音が出来、
熱くなるだけで、動かない。
⇒入れたコマンド
https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/42852875_2143579752568562_6105706910785208320_n.png?_nc_cat=110&oh=7228ebfcf96448c2c4f5da31dd871d99&oe=5C16B808

もしかして、
raspberry pi mouseが不良品の可能性はございますか。
ソフト、OS、device driverには問題ないと存じますが、
いかがでしょうか。

ありがとうございます。

浦摩耶

**Comment by Uramaya** [comment]
こちらは　echo 400 > /dev/rtmotor_raw_l0の結果です。（ビデオ）
https://1drv.ms/v/s!AsMhztcyRB2OvzzODznXAYodJgdP

何も動きません。

**Comment by ryuichiueda** [comment]
ビデオ拝見しましたが、もうちょっとコネクタを深くさせませんか？なんか奥まで刺さってないような気がします。

**Comment by Uramaya** [comment]
上田さん、お返事ありがとうございます。
今してみます。
少々10分後にお返事いたします。（OSをubuntuに変えます）

**Comment by Uramaya** [comment]
上田さん、
ありがとうございます！
Connector を深く差し込んだら
お陰さまで動きました。
ありがとうございます！

**Comment by ryuichiueda** [comment]
よかったです！！
