### ISSUE TITLE
Makefile ：make installし、またrebootした後、ls -l /dev/rt*でファイルが無いと表示

### ISSUE THREAD

**Issue by Uramaya** [ryuichiueda/raspimouse_book_info#19]
上田さん、いつもお世話になっております。
浦です。
実はお聞きしたいことがございまして、
表題の件（本６４ページ）で、Makefileを作成し、そしてmake install　でinstallを実行し、再起動した後、
何故かMakefileが正常に実行されていない様子で、ls -l /dev/rt*でファイルが無いと表示されます。

「missing LSB tags and overrides」というエラーが表示されましたが、
調べたところは、影響がないようで、原因が調べられずに、
お聞きしました。
よろしくお願いいたします。

エビデンス写真：
（１）Makefile 内容
https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/43372283_286163858886422_1376819373813006336_n.png?_nc_cat=102&oh=d3ce1d4a2f5055602f263cfc76608388&oe=5C599F0C
（２）setup.bash内容
https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/43397954_654441018290059_4005884166976569344_n.png?_nc_cat=102&oh=0c9ddd4f8db28c786c7cded8131a21ea&oe=5C5B17BB
（３）Makefile ：make installし、またrebootした後、ls -l /dev/rt*でファイルが無いと表示
https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/43471356_329019860981562_1206354076044886016_n.png?_nc_cat=103&oh=3b2039452e0502ef6f7df7d28ff3de23&oe=5C49478E

https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/43466983_292993394867465_6113475102169366528_n.png?_nc_cat=102&oh=e4526900820294f5413105fd707bd09c&oe=5C4E262B

https://scontent-nrt1-1.xx.fbcdn.net/v/t1.15752-9/43363958_239029106766766_2661945658327433216_n.png?_nc_cat=105&oh=44424e64b88b99ae53ff2cf8e5751dd0&oe=5C57F1CE

浦摩耶

**Comment by ryuichiueda** [comment]
すみません遅くなりました。Makefileは半角スペースではなくてタブでインデントしなければならないのですが、タブになってますでしょうか？
