### ISSUE TITLE
roscoreが実行できない

### ISSUE THREAD

**Issue by tomorrow0911** [ryuichiueda/raspimouse_book_info#2]
p31の./step1.bashを実行すると最後の方に

ls /etc/ros/rosdep/sources.list.d/20-default.list && sudo rm /etc/ros/rosdep/sources.list.d/20-default.list
+ ls /etc/ros/rosdep/sources.list.d/20-default.list
ls: cannot access '/etc/ros/rosdep/sources.list.d/20-default.list': No such file or directory
sudo rosdep init
+ sudo rosdep init
sudo: unable to resolve host ubuntu
ERROR: cannot download default sources list from:
https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
Website may be down.

このように表示されます。roscoreを実行してみると

The program 'roscore' is currently not installed. You can install it by typing:
sudo apt install python-roslaunch

となり、roscoreが実行されませんでした。sudo apt install python-roslaunchを行ってみたのですが

sudo: unable to resolve host ubuntu
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-roslaunch : Depends: python-roslib but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

と表示されroscoreを実行することができませんでした。

**Comment by ryuichiueda** [comment]
ラズパイで次のコマンドを実行してうまくいきますか？

$ wget https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list

どんな出力がされるかみたいです。

**Comment by tomorrow0911** [comment]
試してみたところ下のように出力されました。

--2016-02-11 16:33:19--  https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/sources.list.d/20-default.list
raw.githubusercontent.com (raw.githubusercontent.com) をDNSに問いあわせています... 151.101.72.133
raw.githubusercontent.com (raw.githubusercontent.com)|151.101.72.133|:443 に接続しています... 接続しました。
エラー: raw.githubusercontent.com の証明書(発行者: `CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US')の検証に失敗しました:
  発行された証明書はまだ有効ではありません。
raw.githubusercontent.com に安全の確認をしないで接続するには、`--no-check-certificate' を使ってください。

**Comment by ryuichiueda** [comment]
以下の1,2のどちらかでうまくいきます。（aptのアップデートを止めているなら2は使えません。）

1. step1.bashを編集してcurl に-kオプションをつける。
2. apt updateとapt upgrade

**Comment by tomorrow0911** [comment]
aptのアップデートを止めていたので１を行おうとしたのですが、すでにcurl-kとなっていました。
curl -k https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
sudo apt-get update || echo ""

**Comment by ryuichiueda** [comment]
失礼しました。では、

$ wget --no-check-certificate https://raw.githubusercontent.com/ros/rosdistro/master/ros.key 
$ cat ros.key | sudo apt-key add -

ではどうでしょうか。

**Comment by tomorrow0911** [comment]
やってみたのですが下のようになりました。

ubuntu@ubuntu:~$ wget --no-check-certificate https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
--2016-02-11 16:28:35--  https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
raw.githubusercontent.com (raw.githubusercontent.com) をDNSに問いあわせています... 151.101.72.133
raw.githubusercontent.com (raw.githubusercontent.com)|151.101.72.133|:443 に接続しています... 接続しました。
警告: raw.githubusercontent.com の証明書(発行者: `CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US')の検証に失敗しました:
  発行された証明書はまだ有効ではありません。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 1162 (1.1K) [application/octet-stream]
`ros.key' に保存中

ros.key                       100%[=================================================>]   1.13K  --.-KB/s    in 0s      

2016-02-11 16:28:36 (98.1 MB/s) - `ros.key' へ保存完了 [1162/1162]

ubuntu@ubuntu:~$ cat ros.key | sudo apt-key add -
sudo: ホスト ubuntu の名前解決ができません
gpg: 鍵8CBCF2F2は6259887秒未来にできました (時間旅行か時計の障害でしょう)
gpg: 鍵8CBCF2F2は6259887秒未来にできました (時間旅行か時計の障害でしょう)
OK
ubuntu@ubuntu:~$ roscore
プログラム 'roscore' はまだインストールされていません。 次のように入力することでインストールできます:
sudo apt install python-roslaunch

**Comment by ryuichiueda** [comment]
じゃあ、curlの行の頭に#をつけてもう一度シェルスクリプト（step1.bash）を実行してみてください。

**Comment by ryuichiueda** [comment]
その前に時計を合わせた方が良さそうです。

**Comment by tomorrow0911** [comment]
ネット回線の影響で時計があっていなかったことが原因のようで、別の回線で試してみたところうまくいきました。お騒がせして申し訳ございませんでした。

**Comment by ryuichiueda** [comment]
よかったです。
