### ISSUE TITLE
No image shown on http://<IP>:10000/stream?topic=/face

### ISSUE THREAD

**Issue by csyang6052** [ryuichiueda/raspimouse_book_info#20]
Dear Mr. Ueda,

I was able to run "roslaunch pimouse_vision_control vision_control.launch" without an error.
And, images shown on http://<IP>:10000/stream?topic=/cv_camera/image_raw were normal.
No image shown, however, on http://<IP>:10000/stream?topic=/face
Would you advise any possible item that I can check to debug?

Thank you.

![screenshot from 2018-10-09 20-39-03](https://user-images.githubusercontent.com/16661116/46670312-6c143800-cc04-11e8-9976-9699406de459.png)
![screenshot from 2018-10-09 20-40-20](https://user-images.githubusercontent.com/16661116/46670398-a978c580-cc04-11e8-9eb4-c8c34f141223.png)

**Comment by ryuichiueda** [comment]
Could you type 
```
rostopic list
```
on you terminal and send me the screen shot?

**Comment by csyang6052** [comment]
Instead of using roslaunch, I tried rosrun one more time, still cannot view ~/face .
Here attached is the screen shot, including rostopic list -
Thank you.

![screenshot from 2018-10-10 07-35-33](https://user-images.githubusercontent.com/16661116/46704846-70ba0a00-cc5f-11e8-804f-8d095f20bdee.png)
