### ISSUE TITLE
Instead of using roslaunch, I tried rosrun one more time, still cannot view ~/face .

### ISSUE THREAD

**Issue by csyang6052** [ryuichiueda/raspimouse_book_info#21]
Instead of using roslaunch, I tried rosrun this time.
~/face still showed no image, however.
Here attached is the screen shot, including rostopic list -
Thank you.

![screenshot from 2018-10-10 07-35-33](https://user-images.githubusercontent.com/16661116/46704846-70ba0a00-cc5f-11e8-804f-8d095f20bdee.png)

_Originally posted by @csyang6052 in https://github.com/ryuichiueda/raspimouse_book_info/issue_comments#issuecomment-428389178_

**Comment by ryuichiueda** [comment]
Please try 
```
rostopic echo /face
```

**Comment by csyang6052** [comment]
I tried rosrun pimouse_vision_control face_to_face3.py this time. 
It works now, my face can be detected. 
And, rostopic echo /face output raw numerical data continuously.
I will check codes of face_to_face.py and vision_control.launch again.
Thank you.
![screenshot from 2018-10-10 08-30-55](https://user-images.githubusercontent.com/16661116/46706403-d65dc480-cc66-11e8-8419-e928f6c73194.png)
