### ISSUE TITLE
助言をお願いします。roslaunchが起動できません・・・

### ISSUE THREAD

**Issue by takutohfl** [ryuichiueda/raspimouse_book_info#22]
上田さん、初めまして。野口と申します。
書籍大変参考にさせていただいております。

いま行き詰まってしまっているのでヒントをいただきたいです。
書籍5章のroslaunchとローンチファイルの部分において以下のような症状がでてしまい起動できず、先に進めません＞＜

ubuntu@ubuntu:~$ roslaunch raspimouse_ros raspimouse.launch
 ... logging to /home/ubuntu/.ros/log/b151f84e-d294-11e8-8605-b827eb2dedad/roslaunch-ubuntu-2692.log
 Checking log directory for disk usage. This may take awhile.
 Press Ctrl-C to interrupt
 Done checking log file disk usage. Usage is <1GB.

 cannot resolve host address for machine [localhost]
 The traceback for the exception was written to the log file

roscore等は正常に動かせているのでなぜだかわかりません・・・
IPは固定しています。
何卒よろしくお願いいたします。

**Comment by ryuichiueda** [comment]
cannot resolve host address for machine [localhost]

なので、/etc/hostsにlocalhostのエントリーがないかもしれません

```
127.0.0.1	localhost
```

という行はありますか？

**Comment by takutohfl** [comment]
上田さん
お世話になっております。
野口です。

ご指摘いただいた通り、記述がありませんでした。
固有iPを設定するときにいじってしまったみたいでした。
いま変更したところ、無事に動きました！！！
ありがとうございました！

これからも何卒よろしくお願い致します。
