### ISSUE TITLE
bashrc削除してしまいました

### ISSUE THREAD

**Issue by buffalokusojima** [ryuichiueda/raspimouse_book_info#23]
お初にかかります。
手違いでbashrcを削除してしまい、roscdは愚かその他多数のコマンドが打てなくなりました。
申し訳ないのですが、~/.bashrcの中身を頂けないでしょうか

**Comment by ryuichiueda** [comment]
ROS関係の設定はないですが
https://gist.github.com/ryuichiueda/a790c744450676e6643ecdb9ab6c5303
に置きました。

**Comment by buffalokusojima** [comment]
早速の回答有難うございます。
頂いたファイルの内容を書き込んで実行してみたら、大方の機能は修復しました。
しかし、ご指摘の通りROS関連はエラーのままでした。
そこでもう一度Ubuntu16.04_serverをセットアップしてROS関連のコマンドも修復させました。

おそらくUbuntu16.04_serverセットアップ時に自動でbashrcに記述される以下の部分が足りなかった為だと考えられます。

source /opt/ros/kinetic/setup.bash
export ROS_MASTER_URI=http://localhost:11311
export ROS_HOSTNAME=localhost

今のところこれで以前と同じ作業が出来るようになりました。
お騒がせしました。有難うございます。
