### ISSUE TITLE
20170506_wifiproblem.mdの内容について

### ISSUE THREAD

**Issue by kumanozawa** [ryuichiueda/raspimouse_book_info#25]
上田様、はじめまして。
wifiが接続できない問題で、
RPi-Distroの内容の変更？のせいか、記述通りでは実行できませんでした。

https://github.com/RPi-Distro/firmware-nonfree/tree/master/brcm/brcmfmac43430-sdio.bin

とするとコマンドは実行できたのですが、reboot後のiwconfig でもwlan0は見えませんでした。

https://ubuntu-pi-flavour-maker.org/download/　から入手したイメージ
（ubuntu-16.04-preinstalled-server-armhf+raspi3.img)
を使用したのですが、それによる影響があるのでしょうか？

とりあえずイメージを入れなおし、
1.2: ファームウェアのアップデートだけ止める方法
を試してみたいと思います。

**Comment by ryuichiueda** [comment]
返事遅くなってすみません。今のところちょっと検証に時間が取れないので、こちらに置いてあるUbuntuのイメージをお試しください。3か6が良いかと思われます。

https://b.ueda.tech/?post=20180617_raspi_ubuntu

**Comment by kumanozawa** [comment]
ご回答頂き有難う御座います。

結局 ubuntu-16.04-preinstalled-server-armhf+raspi3.img ではうまくいかなかったため、
回答を頂く前に、上田様のブログより 
ubuntu-16.04-preinstalled-server-armhf+raspi3-upgradable-20171223.img.xz
を入手し

・/etc/hosts へubuntu 追記
・C.13.1の内容で、自動アップデートの抑制
・/etc/network/interfaces へwlan0の追記　（ついでにIPアドレスの固定化）
・/etc/wpa_supplicant/wpa_supplicant.conf にssid等の設定追記
を行った後、本の内容に従ってROSのインストールまで行い、
無線LANによる接続とROSの起動が確認できるところまで来れました。
せっかくなので、このまま読み進めてみたいと思います。有難う御座いました。

余談ですが、ブログの他の記事も拝見させていただきました。
オーストラリアのポッサム、可愛いですね。
２０代の頃、かの国にワーキングホリデーで滞在しておりましたが、
テントにしまい忘れたごみ袋をポッサムとワラルーに荒らされたものでした。
ゴミ漁るくせに可愛いんですよね。

**Comment by ryuichiueda** [comment]
無線つながって良かったです。ブログは・・・あんなのですみません。

**Comment by ryuichiueda** [comment]
そういえばこちらはお試しになりましたか？

https://github.com/ryuichiueda/raspimouse_book_info/blob/master/trouble_reports/wifiproblem.md

**Comment by kumanozawa** [comment]
情報有難う御座います。
頂いた内容は見ておりませんでしたが、
/raw/master/brcm80211/brcm/　が見えなかったため、いろいろ試していた過程で
同じ内容を試みておりました。ですが結果変わらずでした。

**Comment by ryuichiueda** [comment]
承知致しました。情報ありがとうございます。時間を見つけてまた情報アップデートいたします。
