### ISSUE TITLE
2.1.6の設定ファイルの修正について

### ISSUE THREAD

**Issue by shouta0812** [ryuichiueda/raspimouse_book_info#26]
上田様はじめまして。
設定ファイルの修正で、
＄ sudo vi /boot/firmware/config.txt
と打つとエディタが開いてdeviceのコメントが出てくるはずなのですが、全く何も出てこないのですが、そこにdeviceを撃ちこめば設定ファイルの修正ができますか？

**Comment by ryuichiueda** [comment]
もしかしたら問題が修正されていて項目がないのかもしれません。ちなみにどのイメージを使われましたか？

**Comment by shouta0812** [comment]
イメージはubuntu-16.04-preinstalledのP21には書いているイメージファイルを使いました。

**Comment by ryuichiueda** [comment]
今確認したら空になっていました。これからラズパイ3で不具合が出ないか試してみます。

**Comment by ryuichiueda** [comment]
検証しました。ラズパイ3の場合、

```
sudo vi /boot/firmware/config.txt
```

は必要なく、

```
mkdir wifi-firmware
cd wifi-firmware

wget https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm/brcmfmac43430-sdio.bin
wget https://github.com/RPi-Distro/firmware-nonfree/raw/master/brcm/brcmfmac43430-sdio.txt

sudo cp *sdio* /lib/firmware/brcm/
```

でwifiが使えると思います。特に他の問題も出ないようです。

参考: https://wiki.ubuntu.com/ARM/RaspberryPi#WiFi

**Comment by shouta0812** [comment]
ありがとうございます。
