### ISSUE TITLE
USBカメラの画像が表示されない

### ISSUE THREAD

**Issue by ba2vwbus13** [ryuichiueda/raspimouse_book_info#27]
12.4章の方法でブラウザでhttp:////XXX.XXX.XXX.XXX:8000にアクセスしました。
USBカメラの画像が表示されませんでした。センサの値は表示されてます。

Firefoxでは「コンテンツデータ破損エラー　http://XXX.XXX.XXX.XXX:10000/stream?topic=/cv_camera_node/image_raw のウェブサイトで修復不能なネットワークプロトコル違反が発生しました。このページは、データの伝送中にエラーが検出されたため表示できません。」にに
となります。
chromeはそのまま何も表示されませんが、直接、http://XXX.XXX.XXX.XXX:10000/stream?topic=/cv_camera_node/image_raw にアクセスするとUSBカメラの画像が見れます。

ブラウザの設定かと思いますが、もし心当たりがあれば教えて下さい。

**Comment by ryuichiueda** [comment]
返事遅くなってすみません。

> chromeは・・・直接、http://XXX.XXX.XXX.XXX:10000/stream?topic=/cv_camera_node/image_raw にアクセスするとUSBカメラの画像が見れます。

この方法で良いと思います。カメラかROSのモジュールが必要なヘッダを省略してデータ送信するので、ブラウザによっては怒るという現象があります。
