### ISSUE TITLE
現時点でのROS環境に関してのお問い合わせ

### ISSUE THREAD

**Issue by ghost** [ryuichiueda/raspimouse_book_info#28]
御社のWeb情報では下記の3種類がかかれています。
　Raspberry Pi 3は ubuntu16.04とROS kinetic
　RaspberryPi3にUbuntu 14.04とROS indigo
　現状Pi3でUbuntu14.04が動作しないため、ROSを使う場合はPi2でお使いください。

Pi3＋ubuntuxxx＋Melodic Morenia　の情報はお持ちでしょうか？

**Comment by ryuichiueda** [comment]
御社というのはアールティ社さんのことだと思われますが、私は社員ではありません。Ubuntu 18.04まわりについては、このリポジトリの

https://github.com/ryuichiueda/raspimouse_book_info/blob/master/ubuntu18.md

にあります。

**Comment by ghost** [comment]
Ryuichi Ueda様

 

竹村と申します。

 

間違えていまして申し訳ありません。

ご丁寧に情報ありがとうございました。

感謝です。

**Comment by ghost** [comment]
Ryuichi Ueda様

 

テクノ・チップス株式会社

   竹村  と申します。

 

大変恐縮なのですが….

先般　「Raspberry Pi Mouse V2」　で情報を教えていただきました。

上田様の「ubuntu-18.04.2-preinstalled-server-armhf+raspi3-ROS-raspimouse-20190618.img.xz」から

開始しまして、有線はDHCPからアドレスを貰っています。

Wifiは設定して、接続はしているようですが、DHCPからIPアドレスを貰えません。

何か基本的なことを分かっていないように思っているのですが、

アドバイスいただけませんでしょうか？

ボードはraspberrypi-B　です。

よろしくお願いいたします。

 

/etc/netplan/50-cloud-init.yaml　ファイル設定

 

    version: 2

    ethernets:

        eth0:

            dhcp4: true

            match:

                    macaddress: b8:27:eb:～私のボード

            set-name: eth0

 

    wifis:

        wlan0:

            optional: true

            dhcp4: true

            access-points:

                "私のアクセスポイント":

                    password: "パスワード"

 

-----リブート後の状態　------

ubuntu@ubuntu:~$ iwconfig

eth0      no wireless extensions.

lo        no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any

          Mode:Managed  Access Point: Not-Associated   Tx-Power=31 dBm

          Retry short limit:7   RTS thr:off   Fragment thr:off

          Power Management:off

 

ubuntu@ubuntu:~$ ifconfig

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500

        inet 192.168.1.10  netmask 255.255.255.0  broadcast 192.168.1.255

        inet6 2405:6581:1040:6400:ba27:ebff:fe71:5a7a  prefixlen 64  scopeid 0x0<global>

        inet6 fe80::ba27:ebff:fe71:5a7a  prefixlen 64  scopeid 0x20<link>

        ether b8:27:eb:71:5a:7a  txqueuelen 1000  (イーサネット)

        RX packets 341  bytes 35055 (35.0 KB)

        RX errors 0  dropped 106  overruns 0  frame 0

        TX packets 87  bytes 12503 (12.5 KB)

        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

 

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536

        inet 127.0.0.1  netmask 255.0.0.0

        inet6 ::1  prefixlen 128  scopeid 0x10<host>

        loop  txqueuelen 1000  (ローカルループバック)

        RX packets 88  bytes 6648 (6.6 KB)

        RX errors 0  dropped 0  overruns 0  frame 0

        TX packets 88  bytes 6648 (6.6 KB)

        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

 

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500

        ether b8:27:eb:24:0f:2f  txqueuelen 1000  (イーサネット)

        RX packets 0  bytes 0 (0.0 B)

        RX errors 0  dropped 0  overruns 0  frame 0

        TX packets 0  bytes 0 (0.0 B)

        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

 

 

===========================================

  テクノ・チップス株式会社

   竹村  不二夫

  mailto:t_fujio@technochips.co.jp

  220-0072 神奈川県横浜市西区浅間町 3-176-4

  TEL   045-324-6108

  携帯  090-5505-2313

===========================================

 

From: 竹村不二夫 <t_fujio@technochips.co.jp> 
Sent: Friday, January 17, 2020 10:35 AM
To: 'ryuichiueda/raspimouse_book_info' <reply@reply.github.com>; 'ryuichiueda/raspimouse_book_info' <raspimouse_book_info@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [ryuichiueda/raspimouse_book_info] 現時点でのROS環境に関してのお問い合わせ (#28)

 

Ryuichi Ueda様

 

竹村と申します。

 

間違えていまして申し訳ありません。

ご丁寧に情報ありがとうございました。

感謝です。

**Comment by ryuichiueda** [comment]
```
ip a
```

と打って出力を貼り付けていただけないでしょうか。

**Comment by ghost** [comment]
Ryuichi Ueda様

 

テクノ・チップス株式会社

   竹村 です。

 

お手間をおかけいたします。

下記のように表示されました。

 

ubuntu@ubuntu:~$ ip a

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000

    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00

    inet 127.0.0.1/8 scope host lo

       valid_lft forever preferred_lft forever

    inet6 ::1/128 scope host

       valid_lft forever preferred_lft forever

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000

    link/ether b8:27:eb:71:5a:7a brd ff:ff:ff:ff:ff:ff

    inet 192.168.1.10/24 brd 192.168.1.255 scope global dynamic eth0

       valid_lft 1994997316sec preferred_lft 1994997316sec

    inet6 2405:6581:1040:6400:ba27:ebff:fe71:5a7a/64 scope global dynamic mngtmpaddr noprefixroute

       valid_lft 1994997316sec preferred_lft 1994997316sec

    inet6 fe80::ba27:ebff:fe71:5a7a/64 scope link

       valid_lft forever preferred_lft forever

3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel state DOWN group default qlen 1000

    link/ether b8:27:eb:24:0f:2f brd ff:ff:ff:ff:ff:ff

ubuntu@ubuntu:~$

**Comment by ryuichiueda** [comment]
確か有線でIPアドレスをとっていると、無線の方は自動的にとりにいかなかったと記憶しています。

この状態で

```
$ sudo dhclient wlan0
```

と打つとIPアドレスがもらえるかもしれません。また、自動でwlan0にIPアドレスをもらえるようにするには有線の設定を切る必要があるかもしれません。

**Comment by ghost** [comment]
Ryuichi Ueda様

 

テクノ・チップス株式会社

   竹村 です。

 

お手間をおかけいたします。

 

＞$ sudo dhclient wlan0

 

長い時間5分ぐらいデッドロックして、その後も同じ状態した。

 

有線の定義コメントにしてみましたら優先も無線もなくなり　セルフバックだけになってしまいました。

私のところのWifiアクセスポイントが悪いのでしょうか？

アドバイスの方向でもう少し戦ってみます。

**Comment by ryuichiueda** [comment]
sudo dhclient -v wlan0

と間に-vを入れると、情報がとれるかもしれません。

**Comment by ghost** [comment]
Ryuichi Ueda様

 

テクノ・チップス株式会社

   竹村 です。

 

お手間を掛けまして申し訳ありません。

 

dhclient　の使い方と結果確認としてeth0　で行うと

下記のようにDHCPの手順通り取得できていますが、

wlan0　ではDHCPDISCOVERブロードキャストに応答がありません。

Raspiの耳が悪いのでしょうか？

 

もちろん、ラップトップとか、携帯はこのWifiアクセスポイントで動作しています。

Wifi設置が階上のフロアーですので電界強度は低いかもしれません。

アクセスポイントのモードとしては無線有線スルーモードなのでブロードキャストに応答しなことはないと思いますが

原因の範囲を狭める手法を色々教えていただいてありがとうございました。

もう少し悩んでみます。

 

ubuntu@ubuntu:~$ sudo dhclient -v eth0

Internet Systems Consortium DHCP Client 4.3.5

Copyright 2004-2016 Internet Systems Consortium.

All rights reserved.

For info, please visit https://www.isc.org/software/dhcp/

 

Listening on LPF/eth0/b8:27:eb:71:5a:7a

Sending on   LPF/eth0/b8:27:eb:71:5a:7a

Sending on   Socket/fallback

DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0x68d1657a)

DHCPREQUEST of 192.168.1.15 on eth0 to 255.255.255.255 port 67 (xid=0x7a65d168)

DHCPOFFER of 192.168.1.15 from 192.168.1.1

DHCPACK of 192.168.1.15 from 192.168.1.1

bound to 192.168.1.15 -- renewal in 6454 seconds.

ubuntu@ubuntu:~$

 

 

 

ubuntu@ubuntu:~$ sudo dhclient -v wlan0

Internet Systems Consortium DHCP Client 4.3.5

Copyright 2004-2016 Internet Systems Consortium.

All rights reserved.

For info, please visit https://www.isc.org/software/dhcp/

 

Listening on LPF/wlan0/b8:27:eb:24:0f:2f

Sending on   LPF/wlan0/b8:27:eb:24:0f:2f

Sending on   Socket/fallback

DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 3 (xid=0xfe551373)

DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 8 (xid=0xfe551373)

DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 12 (xid=0xfe551373)

DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 18 (xid=0xfe551373)

DHCPDISCOVER on wlan0 to 255.255.255.255 port 67 interval 21 (xid=0xfe551373)

**Comment by ryuichiueda** [comment]
ラズパイ側でwifiの設定が間違っているかもしれません。それから、wifiの規格にもご注意願います。古いラズパイの場合、aではなくてgのはずです。

**Comment by ghost** [comment]
Ryuichi Ueda様

 

テクノ・チップス株式会社

   竹村 です。

 

ありがとうございます。

下記のことですよね。

調べます。

 

規格            周波数帯    最大通信速度

IEEE802.11b     2.4GHz      11Mbps

IEEE802.11g     2.4GHz      54Mbps

IEEE802.11a     5GHz        54Mbps

IEEE802.11n     2.4GHz      600Mbps

                           5GHz

IEEE802.11ac    5GHz        6.9Gbps

IEEE802.11ad    60GHz       6.8Gbps

IEEE802.11ax    2.4GHz      9.6Gbps

                            5GHz
