### ISSUE TITLE
第１０章の10.2.4で、黄色い枠が出力されません。

### ISSUE THREAD

**Issue by ishigem** [ryuichiueda/raspimouse_book_info#3]
10.2.4で、raspimouseの向きは変わって、web上に画像は表示されるのですが、顔に黄色の枠が表示されません。face_to_face.pyを上田先生のsiteからcopyして実行しても表示されませんでした。
動いてはいるのですが、気持ちが悪いので何かチェックすべきところのヒントがあれば教えて下さい。

ラウンチ時のメッセージは以下の感じです。

---
ubuntu@ubuntu:~/catkin_ws/src/pimouse_vision_control/scripts$ roslaunch pimouse_vision_control vision_control.launch 
... logging to /home/ubuntu/.ros/log/af5253de-2707-11e7-8a34-b827eb4ad7e8/roslaunch-ubuntu-9359.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:33650/

SUMMARY
========

PARAMETERS
 * /cv_camera/image_height: 240
 * /cv_camera/image_width: 320
 * /cv_camera/rate: 10.0
 * /mjpeg_server/port: 10000
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    buzzer (pimouse_ros/buzzer.py)
    cv_camera (cv_camera/cv_camera_node)
    face_to_face (pimouse_vision_control/face_to_face.py)
    lightsensors (pimouse_ros/lightsensors.py)
    mjpeg_server (mjpeg_server/mjpeg_server)
    motor (pimouse_ros/motors.py)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[lightsensors-1]: started with pid [9377]
process[buzzer-2]: started with pid [9378]
process[motor-3]: started with pid [9379]
process[cv_camera-4]: started with pid [9380]
process[mjpeg_server-5]: started with pid [9381]
process[face_to_face-6]: started with pid [9382]
[INFO] [1492866944.425935]: detected -0.004909
[INFO] [1492866944.713240]: detected -0.004909
[INFO] [1492866944.994564]: detected -0.009817
[INFO] [1492866945.298363]: detected -0.000000
[INFO] [1492866945.591701]: detected 0.004909
[INFO] [1492866945.874281]: detected 0.009817
---

自分で打ち込んだface_to_face.pyは、こんな感じです。

---
#!/usr/bin/env python
#encoding: utf8
import rospy, cv2, math
from sensor_msgs.msg import Image
from cv_bridge import CvBridge, CvBridgeError
from geometry_msgs.msg import Twist
from std_srvs.srv import Trigger

class FaceToFace():
    def __init__(self):
        self.cmd_vel = rospy.Publisher('cmd_vel', Twist, queue_size=1)
        rospy.wait_for_service('/motor_on')
        rospy.wait_for_service('/motor_off')
        rospy.on_shutdown(rospy.ServiceProxy('/motor_off', Trigger).call)
        rospy.ServiceProxy('/motor_on', Trigger).call()

        sub = rospy.Subscriber("/cv_camera/image_raw", Image, self.get_image)
        self.bridge = CvBridge()
        self.image_org = None
        self.pub = rospy.Publisher("face",Image,queue_size=1)

    def get_image(self,img):
        try:
            self.image_org = self.bridge.imgmsg_to_cv2(img, "bgr8")
        except CvBridgeError as e:
            rospy.logerr(e)

    def monitor(self,rect,org):
        if rect is not None:
            cv2.rectangle(org,tuple(rect[0:2]),tuple(rect[0:2]+rect[2:4]),(0,255,255),4)
        self.pub.publish(self.bridge.cv2_to_imgmsg(org,"bgr8"))
    
    def detect_face(self):
        if self.image_org is None:
            return None

        org = self.image_org

        gimg = cv2.cvtColor(org,cv2.COLOR_BGR2GRAY)
        classifier = "/usr/share/opencv/haarcascades/haarcascade_frontalface_default.xml"
        cascade = cv2.CascadeClassifier(classifier)
        face = cascade.detectMultiScale(gimg,1.1,1,cv2.CASCADE_FIND_BIGGEST_OBJECT)

        if len(face) == 0:
            self.monitor(None,org)
            return None

        r = face[0]
        self.monitor(r,org)
        return r

    def rot_vel(self):
        r = self.detect_face()
        if r is None:
            return 0.0

        wid = self.image_org.shape[1]/2
        pos_x_rate = (r[0] + r[2]/2 - wid)*1.0/wid
        rot = -0.25*pos_x_rate*math.pi
        rospy.loginfo("detected %f",rot)
        return rot

    def control(self):
        m = Twist()
        m.linear.x = 0.0
        m.angular.z = self.rot_vel()
        self.cmd_vel.publish(m)

if __name__ == '__main__':
    rospy.init_node('face_to_face')
    fd = FaceToFace()

    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        fd.control()
        rate.sleep()
---

**Comment by ryuichiueda** [comment]
ブラウザから/cv_camera/image_rawを見ているかもしれません。/faceになっているか確認していただければと。

**Comment by ishigem** [comment]
ビンゴでした。お騒がせしました。

**Comment by ryuichiueda** [comment]
いえいえ、またお気軽にどうぞ。
