### ISSUE TITLE
10.3.3のテストがうまく行きません

### ISSUE THREAD

**Issue by ishigem** [ryuichiueda/raspimouse_book_info#4]
またお世話になります。
10.2.4でmouseは動作したのですが、10.3.3のテストで以下のようなエラーになります。
どこがおかしいのかヒントを頂けると助かります。
たびたびすみません。

```
ubuntu@ubuntu:~/catkin_ws/src/pimouse_vision_control$ rostest pimouse_vision_control test-left-face.launch
... logging to /home/ubuntu/.ros/log/rostest-ubuntu-5639.log
[ROSUNIT] Outputting test results to /home/ubuntu/.ros/test_results/pimouse_vision_control/rostest-launch_test-left-face.xml
[ INFO] [1493298184.961511558]: Opening /home/ubuntu/catkin_ws/src/pimouse_vision_control/bagfiles/face-left.bag

Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.
 [RUNNING]  Bag Time: 1483365776.203758   Duration: 2.015666 / 5.144385               
testtest_face_to_face ... ok

[ROSTEST]-----------------------------------------------------------------------

[pimouse_vision_control.rosunit-test_face_to_face/test_put_freq][ERROR]---------
[Errno 22] Invalid argument
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/ubuntu/catkin_ws/src/pimouse_vision_control/test/test_face_to_face.py", line 19, in test_put_freq
    lhz = self.get_file_freq("l")
  File "/home/ubuntu/catkin_ws/src/pimouse_vision_control/test/test_face_to_face.py", line 8, in get_file_freq
    s = f.readline().rstrip()
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 1
 * FAILURES: 0

```
test-left-face.launchの内容は以下の通りです。

```
<launch>

  <include file="$(find pimouse_ros)/pimouse.launch" />
  <node pkg="rosbag" type="play" name="player" output="screen"
    args="$(find pimouse_vision_control)/bagfiles/face-left.bag" required="true" />
  <node pkg="pimouse_vision_control" name="face_to_face" type="face_to_face.py" output="screen" />
  <test test-name="test_face_to_face" pkg="pimouse_vision_control" type="test_face_to_face.py" args="left" />
</launch>

```

test-face_to_face.pyはbook_infoからコピーして試しました。

**Comment by ryuichiueda** [comment]
テストなのであまり気にしなくても良いかと思いますが、

```
[Errno 22] Invalid argument
```

とありますので、この辺を調べると良いかと。

**Comment by ishigem** [comment]
Invalid argument とありますが、その下の
lhz = self.get_file_freq("l")　とs = f.readline().rstrip()　は、特におかしいところがないような気がして悩んでます。

**Comment by ryuichiueda** [comment]
すみません。反応遅くなりましたがこちらその後いかがですか？

**Comment by ishigem** [comment]
とりあえず放置して先に進んでいます。

**Comment by ba2vwbus13** [comment]
10.3.3のテストで以下のようなエラーメッセージが出ます。
ファイル類はコピーして使ってます。よろしくお願いします。


sudo apt-get install libopencv-dev python-opencv

+sudo apt-get install libopencv-dev python-opencv

Reading package lists... Done

Building dependency tree       

Reading state information... Done

You might want to run 'apt-get -f install' to correct these:

The following packages have unmet dependencies:

 libopencv-dev : Depends: libopencv-calib3d2.4 but it is not going to be installed

                 Depends: libopencv-core2.4 but it is not going to be installed

                 Depends: libopencv-highgui2.4 but it is not going to be installed

                 Depends: libopencv-imgproc2.4 but it is not going to be installed

                 Depends: libopencv-ml2.4 but it is not going to be installed

                 Depends: libopencv-objdetect2.4 but it is not going to be installed

                 Depends: libopencv-core-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-ml-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-imgproc-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-video-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-objdetect-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-highgui-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-calib3d-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-flann-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-features2d-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-legacy-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-contrib-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

                 Depends: libopencv-ts-dev (= 2.4.8+dfsg1-2ubuntu1.2) but it is not going to be installed

**Comment by ryuichiueda** [comment]
今修正中です。少々お待ちください。

**Comment by ryuichiueda** [comment]
Travis CI上で使うUbuntuを16.04にバージョンアップしました。ご連絡ありがとうございました。

* リポジトリ: https://github.com/ryuichiueda/pimouse_vision_control
* テスト: https://travis-ci.org/ryuichiueda/pimouse_vision_control

**Comment by ba2vwbus13** [comment]
大変早急に解決していただき、ありがとうございました。
ところで、テスト最後の方にこのメッセージが出ていますが、理由はわかりますでしょうか。
-----
Traceback (most recent call last):

  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 466, in signal_shutdown

    h()

  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 495, in call

    service_uri = self._get_service_uri(request)

  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 463, in _get_service_uri

    raise ServiceException("service [%s] unavailable"%self.resolved_name)

ServiceException: service [/motor_off] unavailable

**Comment by ryuichiueda** [comment]
ノードを強制終了するときのエラーです。モータのサービスなので実機でちゃんとモータが切れれば大丈夫だと思います（ほんとはこれもテストできれば良いのですが）

**Comment by ba2vwbus13** [comment]
分かりました。ありがとうございました。
